name: test_client
version: 0.0.2

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
    connectanum:
      path: ../../../connectanum-dart/
      # git:
      #   url: https://github.com/oberstet/connectanum-dart.git
      #   ref: master
