name: test_client
version: 0.1.0

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
    convert: ^3.0.0
    uuid: ^3.0.1
    connectanum:
      # load from https://pub.dev
      # ^1.1.5

      # load from local path dependency
      # path: ../../../connectanum-dart/

      # load from upstream GH
      git:
        url: https://github.com/konsultaner/connectanum-dart.git
        ref: master
