#!/bin/bash

export TEST_TMPDIR=/data/work/tmp/testlmdb
NUM=1000000000
# some engines appear to ignore the cache_size and just grab as much RAM as they want
CACHE=34359738368
# some engines honor the cache_size, give them more.
CACHE2=137438953472
WRATE=0
STATS=1048576
DUR=30
TIME="/usr/bin/time -v"

rm -rf $TEST_TMPDIR/*
$TIME ./db_bench_mdb --stats_interval=$STATS --num=$NUM --benchmarks=fillseqbatch --writemap=1
for THREADS in 1 2 4 8 16 32 48 64; do
echo THREADS=$THREADS
$TIME ./db_bench_mdb --stats_interval=$STATS --num=$NUM --benchmarks=readwhilewriting --use_existing_db=1 --writes_per_second=$WRATE --threads=$THREADS --writemap=1 --duration=$DUR
du $TEST_TMPDIR
done
